var TravelPlace = ["Saudia Arabia", "Canada", "Lodon", "Turkey"];
console.log("Original Order: \n");
console.log(TravelPlace);
console.log("\n Alphabetic Order: \n ");
// var sort =  TravelPlace.sort();
console.log(TravelPlace.sort());
console.log("Still Original Order: \n", TravelPlace);
console.log(TravelPlace);
console.log("\n Reverse Order: \n ");
var reverse = TravelPlace.sort().reverse();
console.log(reverse);
console.log("Original Order: \n");
console.log(TravelPlace);
console.log("Reverse Order: \n");
console.log(TravelPlace.reverse());
console.log("Back Original Order: \n");
console.log(TravelPlace.reverse());
console.log("\n Alphabetic Order: \n ");
// var sort =  TravelPlace.sort();
console.log(TravelPlace.sort());
console.log("\nReverse Alphabetic Order: \n ");
// var sort =  TravelPlace.sort();
console.log(TravelPlace.reverse());
